# 03-deployment.yaml (updated version with English comments)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: fsahoncharenkoregistry.azurecr.io/fsa-keycloak:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            # --- Core runtime flags ------------------------------------------------
            - name: KC_AUTO_BUILD           # rebuild build-time options on start-up
              value: "true"
            - name: KC_HTTP_ENABLED         # expose plain HTTP inside the cluster
              value: "true"
            - name: KC_PROXY                # tell Keycloak it is behind a reverse proxy
              value: "edge"
            - name: KC_HTTP_RELATIVE_PATH   # keep the classic /auth context path
              value: "/auth"

            # --- Database connection ---------------------------------------------
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL               # sslmode=require is mandatory for Azure PG
              value: "jdbc:postgresql://fsa-honcharenko-psql.postgres.database.azure.com:5432/keycloak?sslmode=require"
            - name: KC_DB_USERNAME
              value: "fsaadmin"
            - name: KC_DB_PASSWORD
              value: "P@ssword12345"

            # --- Public URLs ------------------------------------------------------
            - name: KC_HOSTNAME             # external hostname served by Ingress
              value: "20.223.168.156.nip.io"
            - name: KC_HOSTNAME_ADMIN_URL   # full URL to the admin console
              value: "https://20.223.168.156.nip.io/auth"

            # --- Bootstrap admin user --------------------------------------------
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
