# 04-service.yaml (без изменений, просто оставляем ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: fsa-keycloak-http
  namespace: app
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
