apiVersion: apps/v1
kind: Deployment
metadata:
  name: honch-backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honch-backend
  template:
    metadata:
      labels:
        app: honch-backend
    spec:
      containers:
      - name: honch-backend
        image: fsahoncharenkoregistry.azurecr.io/fsa-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: SPRING_DATASOURCE_PASSWORD
