
apiVersion: v1
kind: Service
metadata:
  name: honch-backend-svc
  namespace: app
spec:
  type: ClusterIP          # <-- было LoadBalancer
  selector:
    app: honch-backend
  ports:
    - name: http
      port: 8080             # <-- внешний порт для Ingress
      targetPort: 8080
