apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZnNhLWhvbmNoYXJlbmtvLXBzcWwucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tOjU0MzIvZnNhLWRiP3NzbG1vZGU9cmVxdWlyZQ==          
  SPRING_DATASOURCE_USERNAME: ZnNhYWRtaW4=
  SPRING_DATASOURCE_PASSWORD: UEBzc3dvcmQxMjM0NQ==
  db_password: UEBzc3dvcmQxMjM0NQ==


---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  # admin -> admin
  kc_username: YWRtaW4=
  kc_password: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  # FSA.123456
  password: RlNBLjEyMzQ1Ng==

---



apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  runner-registration-token: ""
  runner-token: Z2xydC1oVjU0NzNpRDNrMWRtZkJ4eWJ5dg==
